version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  wait-profiler:
    build: .
    environment:
      MODULE_NAME: wait-profiler
      MYSQL_ENDPOINT: mysql-test:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      EXPORT_PORT: 8083
      OTEL_SERVICE_NAME: wait-profiler
      # New Relic Configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      ENVIRONMENT: production
      CLUSTER_NAME: database-intelligence-cluster
    ports:
      - "8083:8083"
      - "8891:8889"
    depends_on:
      mysql-test:
        condition: service_healthy
    volumes:
      - ./config:/etc/otel:ro
      - ./logs:/tmp/logs
      - wait_profiler_queue_standard:/tmp/wait-profiler-queue-standard
      - wait_profiler_queue_critical:/tmp/wait-profiler-queue-critical
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector-enterprise-working.yaml}"]
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 13133 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wait_profiler_queue_standard:
    driver: local
  wait_profiler_queue_critical:
    driver: local