version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql  # Commented out to prevent MySQL startup failures
    
  sql-intelligence:
    build: .
    environment:
      MODULE_NAME: sql-intelligence
      MYSQL_ENDPOINT: mysql-test:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      EXPORT_PORT: 8082
      METRICS_ENDPOINT: ${METRICS_ENDPOINT:-}
      OTEL_SERVICE_NAME: sql-intelligence
      # New Relic Configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      ENVIRONMENT: production
      CLUSTER_NAME: database-intelligence-cluster
    ports:
      - "8082:8082"
      - "8890:8889"
    depends_on:
      mysql-test:
        condition: service_healthy
    volumes:
      - ./config:/etc/otel:ro
      - ./logs:/tmp/logs
      - sql_intelligence_queue_standard:/tmp/sql-intelligence-queue-standard
      - sql_intelligence_queue_critical:/tmp/sql-intelligence-queue-critical
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector.yaml}"]
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 13133 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sql_intelligence_queue_standard:
    driver: local
  sql_intelligence_queue_critical:
    driver: local