receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.name
        value: business-impact
        action: upsert
      - key: module
        value: business-impact
        action: upsert
      - key: environment
        value: ${env:ENVIRONMENT}
        action: upsert

  attributes/newrelic:
    actions:
      - key: newrelic.source
        value: opentelemetry
        action: insert
      - key: instrumentation.name
        value: mysql-business-impact
        action: insert
      - key: instrumentation.version
        value: "2.0.0"
        action: insert
      - key: instrumentation.provider
        value: opentelemetry
        action: insert

  attributes/entity_synthesis:
    actions:
      - key: entity.type
        value: "MYSQL_BUSINESS_IMPACT"
        action: insert
      - key: entity.guid
        value: "BUSINESS|${env:CLUSTER_NAME}|business-impact"
        action: insert
      - key: entity.name
        value: "business-impact"
        action: insert

exporters:
  otlphttp/newrelic_standard:
    endpoint: ${env:NEW_RELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}
    compression: gzip
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 5
      queue_size: 10000

  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes/newrelic, attributes/entity_synthesis]
      exporters: [otlphttp/newrelic_standard, debug]
  
  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133