receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'metrics-federation'
          scrape_interval: 30s
          static_configs:
            - targets: 
              - '${env:CORE_METRICS_ENDPOINT}'
              - '${env:SQL_INTELLIGENCE_ENDPOINT}'

processors:
  batch:
    timeout: 10s
    
  attributes:
    actions:
      - key: module
        value: performance-advisor
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, attributes]
      exporters: [prometheus, debug]
      
  extensions: [health_check]
  
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
