receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'anomaly-metrics'
          scrape_interval: 15s
          static_configs:
            - targets: ['${env:ANOMALY_DETECTOR_ENDPOINT}']

processors:
  batch:
    timeout: 5s
    
  attributes:
    actions:
      - key: module
        value: alert-manager
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, attributes]
      exporters: [prometheus, debug]
      
  extensions: [health_check]
  
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
