version: '3.8'

services:
  alert-manager:
    build: .
    env_file:
      - ../../shared/config/service-endpoints.env
    environment:
      MODULE_NAME: alert-manager
      EXPORT_PORT: 8089
      OTEL_SERVICE_NAME: alert-manager
      # Alert-specific configuration
      WEBHOOK_ENDPOINT: ${WEBHOOK_ENDPOINT:-http://localhost:9999/alerts}
      ALERT_FILE_PATH: ${ALERT_FILE_PATH:-/tmp/alerts.log}
      # Override specific endpoints if needed
      COLLECTOR_CONFIG: ${COLLECTOR_CONFIG:-collector.yaml}
    ports:
      - "8089:8089"
      - "8897:8889"
      - "4329:4318"  # OTLP HTTP receiver (unique port)
    volumes:
      - ./config:/etc/otel
      - ../../shared/config:/etc/shared
      - /tmp:/tmp  # For alert file logging
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector.yaml}"]