version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  business-impact:
    build: .
    environment:
      MODULE_NAME: business-impact
      MYSQL_ENDPOINT: mysql-test:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      EXPORT_PORT: 8085
      OTEL_SERVICE_NAME: business-impact
      # New Relic Configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      ENVIRONMENT: production
      CLUSTER_NAME: database-intelligence-cluster
      # Module federation endpoints
      SQL_INTELLIGENCE_ENDPOINT: ${SQL_INTELLIGENCE_ENDPOINT:-sql-intelligence:8082}
      CORE_METRICS_ENDPOINT: ${CORE_METRICS_ENDPOINT:-core-metrics:8081}
      # Business impact scoring configuration
      REVENUE_IMPACT_SCORE: "10.0"
      CUSTOMER_IMPACT_SCORE: "8.0"
      OPERATIONS_IMPACT_SCORE: "7.0"
      ANALYTICS_IMPACT_SCORE: "5.0"
      ADMIN_IMPACT_SCORE: "3.0"
      MAX_IMPACT_SCORE: "10.0"
      # SLA thresholds
      SLA_CRITICAL_THRESHOLD: "5.0"
      SLA_WARNING_THRESHOLD: "2.0"
      # Revenue calculations
      BASELINE_REVENUE_PER_SECOND: "1000.0"
      # Boost factors
      REVENUE_BOOST_FACTOR: "1.5"
      CUSTOMER_BOOST_FACTOR: "1.3"
      # Other endpoints
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-otel-collector:4317}
      # Override specific config if needed
      COLLECTOR_CONFIG: ${COLLECTOR_CONFIG:-collector-enterprise-working.yaml}
    ports:
      - "8085:8085"      # Prometheus metrics
      - "8901:8889"      # OTLP gRPC debug
      - "4323:4317"      # OTLP gRPC
      - "4324:4318"      # OTLP HTTP
      - "55683:55679"    # ZPages
      - "6062:6060"      # pprof
      - "8902:8888"      # Internal telemetry
    depends_on:
      mysql-test:
        condition: service_healthy
    volumes:
      - ./config:/etc/otel:ro
      - ./logs:/tmp/logs
      - business_reports:/tmp/business-reports
      - business_impact_queue_standard:/tmp/business-impact-queue-standard
      - business_impact_queue_critical:/tmp/business-impact-queue-critical
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector-enterprise-working.yaml}"]
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 13133 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - db-intelligence

volumes:
  business_reports:
    driver: local
  business_impact_queue_standard:
    driver: local
  business_impact_queue_critical:
    driver: local

networks:
  db-intelligence:
    driver: bridge